#!/bin/sh
R CMD BATCH --vanilla sim_105.R
R CMD BATCH --vanilla sim_129.R
R CMD BATCH --vanilla sim_130.R
R CMD BATCH --vanilla sim_144.R
R CMD BATCH --vanilla sim_187.R
R CMD BATCH --vanilla sim_204.R
R CMD BATCH --vanilla sim_226.R
R CMD BATCH --vanilla sim_231.R
R CMD BATCH --vanilla sim_238.R
R CMD BATCH --vanilla sim_270.R
R CMD BATCH --vanilla sim_273.R
R CMD BATCH --vanilla sim_277.R
R CMD BATCH --vanilla sim_289.R
R CMD BATCH --vanilla sim_297.R
R CMD BATCH --vanilla sim_299.R
R CMD BATCH --vanilla sim_301.R
R CMD BATCH --vanilla sim_304.R
R CMD BATCH --vanilla sim_307.R
R CMD BATCH --vanilla sim_330.R
R CMD BATCH --vanilla sim_349.R
R CMD BATCH --vanilla sim_350.R
R CMD BATCH --vanilla sim_358.R
R CMD BATCH --vanilla sim_37.R
R CMD BATCH --vanilla sim_371.R
R CMD BATCH --vanilla sim_375.R
R CMD BATCH --vanilla sim_381.R
R CMD BATCH --vanilla sim_390.R
R CMD BATCH --vanilla sim_392.R
R CMD BATCH --vanilla sim_416.R
R CMD BATCH --vanilla sim_429.R
R CMD BATCH --vanilla sim_447.R
R CMD BATCH --vanilla sim_45.R
R CMD BATCH --vanilla sim_456.R
R CMD BATCH --vanilla sim_463.R
R CMD BATCH --vanilla sim_464.R
R CMD BATCH --vanilla sim_466.R
R CMD BATCH --vanilla sim_471.R
R CMD BATCH --vanilla sim_480.R
R CMD BATCH --vanilla sim_484.R
R CMD BATCH --vanilla sim_494.R
R CMD BATCH --vanilla sim_502.R
R CMD BATCH --vanilla sim_509.R
R CMD BATCH --vanilla sim_515.R
R CMD BATCH --vanilla sim_549.R
R CMD BATCH --vanilla sim_550.R
R CMD BATCH --vanilla sim_556.R
R CMD BATCH --vanilla sim_566.R
R CMD BATCH --vanilla sim_575.R
R CMD BATCH --vanilla sim_587.R
R CMD BATCH --vanilla sim_591.R
R CMD BATCH --vanilla sim_597.R
R CMD BATCH --vanilla sim_622.R
R CMD BATCH --vanilla sim_624.R
R CMD BATCH --vanilla sim_641.R
R CMD BATCH --vanilla sim_643.R
R CMD BATCH --vanilla sim_646.R
R CMD BATCH --vanilla sim_648.R
R CMD BATCH --vanilla sim_661.R
R CMD BATCH --vanilla sim_668.R
R CMD BATCH --vanilla sim_676.R
R CMD BATCH --vanilla sim_679.R
R CMD BATCH --vanilla sim_683.R
R CMD BATCH --vanilla sim_690.R
R CMD BATCH --vanilla sim_710.R
R CMD BATCH --vanilla sim_717.R
R CMD BATCH --vanilla sim_720.R
R CMD BATCH --vanilla sim_725.R
R CMD BATCH --vanilla sim_729.R
R CMD BATCH --vanilla sim_754.R
R CMD BATCH --vanilla sim_756.R
R CMD BATCH --vanilla sim_774.R
R CMD BATCH --vanilla sim_775.R
R CMD BATCH --vanilla sim_786.R
R CMD BATCH --vanilla sim_788.R
R CMD BATCH --vanilla sim_8.R
R CMD BATCH --vanilla sim_818.R
R CMD BATCH --vanilla sim_823.R
R CMD BATCH --vanilla sim_836.R
R CMD BATCH --vanilla sim_839.R
R CMD BATCH --vanilla sim_841.R
R CMD BATCH --vanilla sim_851.R
R CMD BATCH --vanilla sim_853.R
R CMD BATCH --vanilla sim_862.R
R CMD BATCH --vanilla sim_873.R
R CMD BATCH --vanilla sim_874.R
R CMD BATCH --vanilla sim_878.R
R CMD BATCH --vanilla sim_886.R
R CMD BATCH --vanilla sim_887.R
R CMD BATCH --vanilla sim_893.R
R CMD BATCH --vanilla sim_9.R
R CMD BATCH --vanilla sim_930.R
R CMD BATCH --vanilla sim_936.R
R CMD BATCH --vanilla sim_950.R
R CMD BATCH --vanilla sim_961.R
R CMD BATCH --vanilla sim_973.R
R CMD BATCH --vanilla sim_975.R
R CMD BATCH --vanilla sim_977.R
R CMD BATCH --vanilla sim_978.R
R CMD BATCH --vanilla sim_989.R
R CMD BATCH --vanilla sim_999.R
