#!/bin/sh
R CMD BATCH --vanilla sim_104.R
R CMD BATCH --vanilla sim_105.R
R CMD BATCH --vanilla sim_110.R
R CMD BATCH --vanilla sim_111.R
R CMD BATCH --vanilla sim_121.R
R CMD BATCH --vanilla sim_129.R
R CMD BATCH --vanilla sim_141.R
R CMD BATCH --vanilla sim_176.R
R CMD BATCH --vanilla sim_187.R
R CMD BATCH --vanilla sim_193.R
R CMD BATCH --vanilla sim_198.R
R CMD BATCH --vanilla sim_22.R
R CMD BATCH --vanilla sim_248.R
R CMD BATCH --vanilla sim_252.R
R CMD BATCH --vanilla sim_270.R
R CMD BATCH --vanilla sim_277.R
R CMD BATCH --vanilla sim_280.R
R CMD BATCH --vanilla sim_287.R
R CMD BATCH --vanilla sim_29.R
R CMD BATCH --vanilla sim_299.R
R CMD BATCH --vanilla sim_304.R
R CMD BATCH --vanilla sim_307.R
R CMD BATCH --vanilla sim_326.R
R CMD BATCH --vanilla sim_330.R
R CMD BATCH --vanilla sim_343.R
R CMD BATCH --vanilla sim_345.R
R CMD BATCH --vanilla sim_37.R
R CMD BATCH --vanilla sim_371.R
R CMD BATCH --vanilla sim_375.R
R CMD BATCH --vanilla sim_378.R
R CMD BATCH --vanilla sim_382.R
R CMD BATCH --vanilla sim_39.R
R CMD BATCH --vanilla sim_390.R
R CMD BATCH --vanilla sim_40.R
R CMD BATCH --vanilla sim_402.R
R CMD BATCH --vanilla sim_404.R
R CMD BATCH --vanilla sim_422.R
R CMD BATCH --vanilla sim_435.R
R CMD BATCH --vanilla sim_45.R
R CMD BATCH --vanilla sim_465.R
R CMD BATCH --vanilla sim_471.R
R CMD BATCH --vanilla sim_485.R
R CMD BATCH --vanilla sim_492.R
R CMD BATCH --vanilla sim_494.R
R CMD BATCH --vanilla sim_499.R
R CMD BATCH --vanilla sim_506.R
R CMD BATCH --vanilla sim_509.R
R CMD BATCH --vanilla sim_525.R
R CMD BATCH --vanilla sim_526.R
R CMD BATCH --vanilla sim_532.R
R CMD BATCH --vanilla sim_537.R
R CMD BATCH --vanilla sim_545.R
R CMD BATCH --vanilla sim_554.R
R CMD BATCH --vanilla sim_556.R
R CMD BATCH --vanilla sim_557.R
R CMD BATCH --vanilla sim_582.R
R CMD BATCH --vanilla sim_591.R
R CMD BATCH --vanilla sim_597.R
R CMD BATCH --vanilla sim_601.R
R CMD BATCH --vanilla sim_615.R
R CMD BATCH --vanilla sim_616.R
R CMD BATCH --vanilla sim_620.R
R CMD BATCH --vanilla sim_642.R
R CMD BATCH --vanilla sim_661.R
R CMD BATCH --vanilla sim_672.R
R CMD BATCH --vanilla sim_677.R
R CMD BATCH --vanilla sim_679.R
R CMD BATCH --vanilla sim_684.R
R CMD BATCH --vanilla sim_718.R
R CMD BATCH --vanilla sim_725.R
R CMD BATCH --vanilla sim_729.R
R CMD BATCH --vanilla sim_733.R
R CMD BATCH --vanilla sim_742.R
R CMD BATCH --vanilla sim_767.R
R CMD BATCH --vanilla sim_775.R
R CMD BATCH --vanilla sim_791.R
R CMD BATCH --vanilla sim_801.R
R CMD BATCH --vanilla sim_802.R
R CMD BATCH --vanilla sim_808.R
R CMD BATCH --vanilla sim_810.R
R CMD BATCH --vanilla sim_836.R
R CMD BATCH --vanilla sim_838.R
R CMD BATCH --vanilla sim_84.R
R CMD BATCH --vanilla sim_841.R
R CMD BATCH --vanilla sim_843.R
R CMD BATCH --vanilla sim_852.R
R CMD BATCH --vanilla sim_871.R
R CMD BATCH --vanilla sim_874.R
R CMD BATCH --vanilla sim_878.R
R CMD BATCH --vanilla sim_889.R
R CMD BATCH --vanilla sim_924.R
R CMD BATCH --vanilla sim_930.R
R CMD BATCH --vanilla sim_931.R
R CMD BATCH --vanilla sim_940.R
R CMD BATCH --vanilla sim_950.R
R CMD BATCH --vanilla sim_965.R
R CMD BATCH --vanilla sim_977.R
R CMD BATCH --vanilla sim_978.R
R CMD BATCH --vanilla sim_984.R
R CMD BATCH --vanilla sim_987.R
