#!/bin/sh
R CMD BATCH --vanilla sim_logistic_755.R
R CMD BATCH --vanilla sim_knn_27.R
R CMD BATCH --vanilla sim_knn_973.R
R CMD BATCH --vanilla sim_logistic_104.R
R CMD BATCH --vanilla sim_knn_65.R
R CMD BATCH --vanilla sim_knn_381.R
R CMD BATCH --vanilla sim_logistic_668.R
R CMD BATCH --vanilla sim_logistic_124.R
R CMD BATCH --vanilla sim_logistic_549.R
R CMD BATCH --vanilla sim_knn_305.R
R CMD BATCH --vanilla sim_knn_663.R
R CMD BATCH --vanilla sim_logistic_126.R
R CMD BATCH --vanilla sim_logistic_422.R
R CMD BATCH --vanilla sim_knn_20.R
R CMD BATCH --vanilla sim_knn_654.R
R CMD BATCH --vanilla sim_knn_976.R
R CMD BATCH --vanilla sim_logistic_474.R
R CMD BATCH --vanilla sim_knn_304.R
R CMD BATCH --vanilla sim_knn_720.R
R CMD BATCH --vanilla sim_logistic_284.R
R CMD BATCH --vanilla sim_knn_790.R
R CMD BATCH --vanilla sim_knn_277.R
R CMD BATCH --vanilla sim_logistic_490.R
R CMD BATCH --vanilla sim_knn_327.R
R CMD BATCH --vanilla sim_knn_176.R
R CMD BATCH --vanilla sim_logistic_338.R
R CMD BATCH --vanilla sim_logistic_606.R
R CMD BATCH --vanilla sim_knn_812.R
R CMD BATCH --vanilla sim_knn_181.R
R CMD BATCH --vanilla sim_knn_29.R
R CMD BATCH --vanilla sim_knn_664.R
R CMD BATCH --vanilla sim_logistic_371.R
R CMD BATCH --vanilla sim_knn_512.R
R CMD BATCH --vanilla sim_logistic_679.R
R CMD BATCH --vanilla sim_knn_966.R
R CMD BATCH --vanilla sim_knn_758.R
R CMD BATCH --vanilla sim_knn_116.R
R CMD BATCH --vanilla sim_logistic_962.R
R CMD BATCH --vanilla sim_knn_658.R
R CMD BATCH --vanilla sim_logistic_504.R
R CMD BATCH --vanilla sim_knn_266.R
R CMD BATCH --vanilla sim_knn_259.R
R CMD BATCH --vanilla sim_knn_554.R
R CMD BATCH --vanilla sim_logistic_601.R
R CMD BATCH --vanilla sim_knn_193.R
R CMD BATCH --vanilla sim_knn_371.R
R CMD BATCH --vanilla sim_knn_31.R
R CMD BATCH --vanilla sim_logistic_175.R
R CMD BATCH --vanilla sim_logistic_545.R
R CMD BATCH --vanilla sim_knn_690.R
R CMD BATCH --vanilla sim_logistic_508.R
R CMD BATCH --vanilla sim_knn_109.R
R CMD BATCH --vanilla sim_logistic_965.R
R CMD BATCH --vanilla sim_knn_357.R
R CMD BATCH --vanilla sim_knn_883.R
R CMD BATCH --vanilla sim_knn_547.R
R CMD BATCH --vanilla sim_logistic_976.R
R CMD BATCH --vanilla sim_logistic_628.R
R CMD BATCH --vanilla sim_knn_557.R
R CMD BATCH --vanilla sim_logistic_653.R
R CMD BATCH --vanilla sim_logistic_568.R
R CMD BATCH --vanilla sim_knn_619.R
R CMD BATCH --vanilla sim_knn_514.R
R CMD BATCH --vanilla sim_knn_638.R
R CMD BATCH --vanilla sim_knn_668.R
R CMD BATCH --vanilla sim_logistic_742.R
R CMD BATCH --vanilla sim_knn_85.R
R CMD BATCH --vanilla sim_logistic_135.R
R CMD BATCH --vanilla sim_logistic_493.R
R CMD BATCH --vanilla sim_logistic_553.R
R CMD BATCH --vanilla sim_knn_340.R
R CMD BATCH --vanilla sim_knn_980.R
R CMD BATCH --vanilla sim_knn_464.R
R CMD BATCH --vanilla sim_knn_822.R
R CMD BATCH --vanilla sim_logistic_219.R
R CMD BATCH --vanilla sim_knn_435.R
R CMD BATCH --vanilla sim_logistic_192.R
R CMD BATCH --vanilla sim_knn_209.R
R CMD BATCH --vanilla sim_knn_731.R
R CMD BATCH --vanilla sim_logistic_233.R
R CMD BATCH --vanilla sim_logistic_115.R
R CMD BATCH --vanilla sim_knn_217.R
R CMD BATCH --vanilla sim_logistic_584.R
R CMD BATCH --vanilla sim_logistic_378.R
R CMD BATCH --vanilla sim_knn_878.R
R CMD BATCH --vanilla sim_logistic_712.R
R CMD BATCH --vanilla sim_knn_495.R
R CMD BATCH --vanilla sim_knn_762.R
R CMD BATCH --vanilla sim_knn_218.R
R CMD BATCH --vanilla sim_logistic_307.R
R CMD BATCH --vanilla sim_logistic_643.R
R CMD BATCH --vanilla sim_knn_539.R
R CMD BATCH --vanilla sim_knn_479.R
R CMD BATCH --vanilla sim_logistic_290.R
R CMD BATCH --vanilla sim_logistic_932.R
R CMD BATCH --vanilla sim_logistic_918.R
R CMD BATCH --vanilla sim_logistic_862.R
R CMD BATCH --vanilla sim_knn_796.R
R CMD BATCH --vanilla sim_logistic_832.R
R CMD BATCH --vanilla sim_knn_920.R
R CMD BATCH --vanilla sim_knn_384.R
R CMD BATCH --vanilla sim_knn_127.R
R CMD BATCH --vanilla sim_knn_448.R
R CMD BATCH --vanilla sim_knn_158.R
R CMD BATCH --vanilla sim_logistic_349.R
R CMD BATCH --vanilla sim_logistic_885.R
R CMD BATCH --vanilla sim_knn_483.R
R CMD BATCH --vanilla sim_knn_377.R
R CMD BATCH --vanilla sim_logistic_473.R
R CMD BATCH --vanilla sim_logistic_1.R
R CMD BATCH --vanilla sim_knn_721.R
R CMD BATCH --vanilla sim_knn_60.R
R CMD BATCH --vanilla sim_logistic_33.R
R CMD BATCH --vanilla sim_logistic_444.R
R CMD BATCH --vanilla sim_knn_15.R
R CMD BATCH --vanilla sim_logistic_37.R
R CMD BATCH --vanilla sim_logistic_634.R
R CMD BATCH --vanilla sim_logistic_767.R
R CMD BATCH --vanilla sim_knn_910.R
R CMD BATCH --vanilla sim_logistic_234.R
R CMD BATCH --vanilla sim_knn_506.R
R CMD BATCH --vanilla sim_logistic_457.R
R CMD BATCH --vanilla sim_logistic_181.R
R CMD BATCH --vanilla sim_knn_72.R
R CMD BATCH --vanilla sim_knn_977.R
R CMD BATCH --vanilla sim_logistic_216.R
R CMD BATCH --vanilla sim_knn_955.R
R CMD BATCH --vanilla sim_logistic_42.R
R CMD BATCH --vanilla sim_knn_647.R
R CMD BATCH --vanilla sim_knn_264.R
R CMD BATCH --vanilla sim_knn_994.R
R CMD BATCH --vanilla sim_logistic_25.R
R CMD BATCH --vanilla sim_logistic_282.R
R CMD BATCH --vanilla sim_logistic_646.R
R CMD BATCH --vanilla sim_logistic_900.R
R CMD BATCH --vanilla sim_logistic_961.R
R CMD BATCH --vanilla sim_logistic_73.R
R CMD BATCH --vanilla sim_logistic_413.R
R CMD BATCH --vanilla sim_knn_480.R
R CMD BATCH --vanilla sim_knn_764.R
R CMD BATCH --vanilla sim_knn_404.R
R CMD BATCH --vanilla sim_logistic_810.R
R CMD BATCH --vanilla sim_knn_616.R
R CMD BATCH --vanilla sim_knn_770.R
R CMD BATCH --vanilla sim_knn_733.R
R CMD BATCH --vanilla sim_logistic_139.R
R CMD BATCH --vanilla sim_knn_536.R
R CMD BATCH --vanilla sim_logistic_670.R
R CMD BATCH --vanilla sim_logistic_129.R
R CMD BATCH --vanilla sim_logistic_280.R
R CMD BATCH --vanilla sim_logistic_798.R
R CMD BATCH --vanilla sim_knn_556.R
R CMD BATCH --vanilla sim_logistic_89.R
R CMD BATCH --vanilla sim_knn_686.R
R CMD BATCH --vanilla sim_logistic_471.R
R CMD BATCH --vanilla sim_knn_302.R
R CMD BATCH --vanilla sim_knn_161.R
R CMD BATCH --vanilla sim_knn_742.R
R CMD BATCH --vanilla sim_knn_610.R
R CMD BATCH --vanilla sim_knn_504.R
R CMD BATCH --vanilla sim_knn_129.R
R CMD BATCH --vanilla sim_knn_940.R
R CMD BATCH --vanilla sim_knn_777.R
R CMD BATCH --vanilla sim_knn_820.R
R CMD BATCH --vanilla sim_knn_650.R
R CMD BATCH --vanilla sim_knn_69.R
R CMD BATCH --vanilla sim_knn_268.R
R CMD BATCH --vanilla sim_knn_693.R
R CMD BATCH --vanilla sim_knn_737.R
R CMD BATCH --vanilla sim_logistic_537.R
R CMD BATCH --vanilla sim_logistic_789.R
R CMD BATCH --vanilla sim_knn_284.R
R CMD BATCH --vanilla sim_logistic_846.R
R CMD BATCH --vanilla sim_knn_84.R
R CMD BATCH --vanilla sim_knn_577.R
R CMD BATCH --vanilla sim_knn_962.R
R CMD BATCH --vanilla sim_logistic_735.R
R CMD BATCH --vanilla sim_logistic_22.R
R CMD BATCH --vanilla sim_logistic_180.R
R CMD BATCH --vanilla sim_knn_533.R
R CMD BATCH --vanilla sim_knn_838.R
R CMD BATCH --vanilla sim_knn_81.R
R CMD BATCH --vanilla sim_knn_48.R
R CMD BATCH --vanilla sim_knn_41.R
R CMD BATCH --vanilla sim_logistic_995.R
R CMD BATCH --vanilla sim_knn_493.R
R CMD BATCH --vanilla sim_logistic_119.R
R CMD BATCH --vanilla sim_knn_998.R
R CMD BATCH --vanilla sim_logistic_848.R
R CMD BATCH --vanilla sim_knn_821.R
R CMD BATCH --vanilla sim_logistic_958.R
R CMD BATCH --vanilla sim_knn_736.R
R CMD BATCH --vanilla sim_knn_545.R
R CMD BATCH --vanilla sim_knn_252.R
R CMD BATCH --vanilla sim_knn_950.R
R CMD BATCH --vanilla sim_logistic_959.R
R CMD BATCH --vanilla sim_knn_931.R
R CMD BATCH --vanilla sim_knn_988.R
R CMD BATCH --vanilla sim_logistic_442.R
R CMD BATCH --vanilla sim_logistic_570.R
R CMD BATCH --vanilla sim_logistic_799.R
R CMD BATCH --vanilla sim_logistic_138.R
R CMD BATCH --vanilla sim_knn_959.R
R CMD BATCH --vanilla sim_logistic_687.R
R CMD BATCH --vanilla sim_logistic_823.R
R CMD BATCH --vanilla sim_logistic_71.R
R CMD BATCH --vanilla sim_knn_271.R
R CMD BATCH --vanilla sim_knn_111.R
R CMD BATCH --vanilla sim_logistic_925.R
R CMD BATCH --vanilla sim_logistic_414.R
R CMD BATCH --vanilla sim_knn_358.R
R CMD BATCH --vanilla sim_knn_148.R
R CMD BATCH --vanilla sim_logistic_132.R
R CMD BATCH --vanilla sim_knn_453.R
R CMD BATCH --vanilla sim_logistic_663.R
R CMD BATCH --vanilla sim_knn_761.R
R CMD BATCH --vanilla sim_logistic_993.R
R CMD BATCH --vanilla sim_knn_338.R
R CMD BATCH --vanilla sim_knn_857.R
R CMD BATCH --vanilla sim_knn_175.R
R CMD BATCH --vanilla sim_knn_604.R
R CMD BATCH --vanilla sim_logistic_91.R
R CMD BATCH --vanilla sim_knn_839.R
R CMD BATCH --vanilla sim_knn_173.R
R CMD BATCH --vanilla sim_knn_291.R
R CMD BATCH --vanilla sim_logistic_852.R
R CMD BATCH --vanilla sim_logistic_340.R
R CMD BATCH --vanilla sim_logistic_740.R
R CMD BATCH --vanilla sim_knn_682.R
R CMD BATCH --vanilla sim_knn_805.R
R CMD BATCH --vanilla sim_knn_679.R
R CMD BATCH --vanilla sim_knn_485.R
R CMD BATCH --vanilla sim_logistic_597.R
R CMD BATCH --vanilla sim_logistic_824.R
R CMD BATCH --vanilla sim_logistic_721.R
R CMD BATCH --vanilla sim_knn_981.R
R CMD BATCH --vanilla sim_knn_819.R
R CMD BATCH --vanilla sim_knn_295.R
R CMD BATCH --vanilla sim_logistic_235.R
R CMD BATCH --vanilla sim_knn_119.R
R CMD BATCH --vanilla sim_knn_634.R
R CMD BATCH --vanilla sim_logistic_369.R
R CMD BATCH --vanilla sim_knn_222.R
R CMD BATCH --vanilla sim_logistic_802.R
R CMD BATCH --vanilla sim_logistic_955.R
R CMD BATCH --vanilla sim_knn_767.R
R CMD BATCH --vanilla sim_knn_725.R
R CMD BATCH --vanilla sim_logistic_99.R
R CMD BATCH --vanilla sim_logistic_675.R
R CMD BATCH --vanilla sim_logistic_19.R
R CMD BATCH --vanilla sim_logistic_208.R
R CMD BATCH --vanilla sim_logistic_108.R
R CMD BATCH --vanilla sim_knn_568.R
R CMD BATCH --vanilla sim_logistic_218.R
R CMD BATCH --vanilla sim_knn_467.R
R CMD BATCH --vanilla sim_logistic_966.R
R CMD BATCH --vanilla sim_knn_607.R
R CMD BATCH --vanilla sim_logistic_948.R
R CMD BATCH --vanilla sim_knn_628.R
R CMD BATCH --vanilla sim_logistic_140.R
R CMD BATCH --vanilla sim_knn_141.R
R CMD BATCH --vanilla sim_logistic_271.R
R CMD BATCH --vanilla sim_knn_104.R
R CMD BATCH --vanilla sim_logistic_684.R
R CMD BATCH --vanilla sim_knn_220.R
R CMD BATCH --vanilla sim_logistic_833.R
R CMD BATCH --vanilla sim_logistic_494.R
R CMD BATCH --vanilla sim_knn_201.R
R CMD BATCH --vanilla sim_knn_544.R
R CMD BATCH --vanilla sim_logistic_920.R
R CMD BATCH --vanilla sim_knn_329.R
R CMD BATCH --vanilla sim_logistic_526.R
R CMD BATCH --vanilla sim_logistic_987.R
R CMD BATCH --vanilla sim_logistic_818.R
R CMD BATCH --vanilla sim_knn_138.R
R CMD BATCH --vanilla sim_knn_932.R
R CMD BATCH --vanilla sim_knn_907.R
R CMD BATCH --vanilla sim_logistic_435.R
R CMD BATCH --vanilla sim_logistic_484.R
R CMD BATCH --vanilla sim_knn_694.R
R CMD BATCH --vanilla sim_logistic_801.R
R CMD BATCH --vanilla sim_logistic_775.R
R CMD BATCH --vanilla sim_logistic_719.R
R CMD BATCH --vanilla sim_knn_79.R
R CMD BATCH --vanilla sim_knn_941.R
R CMD BATCH --vanilla sim_knn_436.R
R CMD BATCH --vanilla sim_logistic_440.R
R CMD BATCH --vanilla sim_knn_494.R
R CMD BATCH --vanilla sim_knn_938.R
R CMD BATCH --vanilla sim_logistic_611.R
R CMD BATCH --vanilla sim_logistic_928.R
R CMD BATCH --vanilla sim_logistic_169.R
R CMD BATCH --vanilla sim_logistic_968.R
R CMD BATCH --vanilla sim_logistic_247.R
R CMD BATCH --vanilla sim_logistic_749.R
R CMD BATCH --vanilla sim_knn_894.R
R CMD BATCH --vanilla sim_knn_687.R
R CMD BATCH --vanilla sim_knn_3.R
R CMD BATCH --vanilla sim_knn_169.R
R CMD BATCH --vanilla sim_logistic_693.R
R CMD BATCH --vanilla sim_logistic_697.R
R CMD BATCH --vanilla sim_knn_330.R
R CMD BATCH --vanilla sim_knn_520.R
R CMD BATCH --vanilla sim_knn_718.R
R CMD BATCH --vanilla sim_logistic_895.R
R CMD BATCH --vanilla sim_logistic_572.R
R CMD BATCH --vanilla sim_knn_930.R
R CMD BATCH --vanilla sim_knn_369.R
R CMD BATCH --vanilla sim_logistic_40.R
R CMD BATCH --vanilla sim_knn_349.R
R CMD BATCH --vanilla sim_logistic_788.R
R CMD BATCH --vanilla sim_logistic_488.R
R CMD BATCH --vanilla sim_knn_549.R
R CMD BATCH --vanilla sim_knn_925.R
R CMD BATCH --vanilla sim_knn_132.R
R CMD BATCH --vanilla sim_logistic_737.R
R CMD BATCH --vanilla sim_knn_642.R
R CMD BATCH --vanilla sim_logistic_296.R
R CMD BATCH --vanilla sim_knn_346.R
R CMD BATCH --vanilla sim_logistic_500.R
R CMD BATCH --vanilla sim_logistic_56.R
R CMD BATCH --vanilla sim_logistic_315.R
R CMD BATCH --vanilla sim_knn_808.R
R CMD BATCH --vanilla sim_logistic_111.R
R CMD BATCH --vanilla sim_knn_620.R
R CMD BATCH --vanilla sim_logistic_354.R
R CMD BATCH --vanilla sim_knn_701.R
R CMD BATCH --vanilla sim_logistic_725.R
R CMD BATCH --vanilla sim_logistic_222.R
R CMD BATCH --vanilla sim_knn_470.R
R CMD BATCH --vanilla sim_knn_978.R
R CMD BATCH --vanilla sim_logistic_582.R
R CMD BATCH --vanilla sim_knn_108.R
R CMD BATCH --vanilla sim_logistic_718.R
R CMD BATCH --vanilla sim_logistic_702.R
R CMD BATCH --vanilla sim_knn_985.R
R CMD BATCH --vanilla sim_logistic_857.R
R CMD BATCH --vanilla sim_logistic_630.R
R CMD BATCH --vanilla sim_logistic_843.R
R CMD BATCH --vanilla sim_knn_622.R
R CMD BATCH --vanilla sim_logistic_361.R
R CMD BATCH --vanilla sim_logistic_821.R
R CMD BATCH --vanilla sim_logistic_512.R
R CMD BATCH --vanilla sim_knn_665.R
R CMD BATCH --vanilla sim_knn_928.R
R CMD BATCH --vanilla sim_knn_422.R
R CMD BATCH --vanilla sim_logistic_978.R
R CMD BATCH --vanilla sim_knn_334.R
R CMD BATCH --vanilla sim_logistic_261.R
R CMD BATCH --vanilla sim_logistic_805.R
R CMD BATCH --vanilla sim_logistic_938.R
R CMD BATCH --vanilla sim_logistic_375.R
R CMD BATCH --vanilla sim_logistic_407.R
R CMD BATCH --vanilla sim_knn_440.R
R CMD BATCH --vanilla sim_logistic_121.R
R CMD BATCH --vanilla sim_logistic_772.R
R CMD BATCH --vanilla sim_knn_433.R
R CMD BATCH --vanilla sim_knn_198.R
R CMD BATCH --vanilla sim_logistic_907.R
R CMD BATCH --vanilla sim_logistic_884.R
R CMD BATCH --vanilla sim_logistic_855.R
R CMD BATCH --vanilla sim_logistic_164.R
R CMD BATCH --vanilla sim_logistic_880.R
R CMD BATCH --vanilla sim_knn_316.R
R CMD BATCH --vanilla sim_knn_601.R
R CMD BATCH --vanilla sim_knn_150.R
R CMD BATCH --vanilla sim_knn_71.R
R CMD BATCH --vanilla sim_knn_110.R
R CMD BATCH --vanilla sim_logistic_988.R
R CMD BATCH --vanilla sim_logistic_887.R
R CMD BATCH --vanilla sim_logistic_77.R
R CMD BATCH --vanilla sim_knn_972.R
R CMD BATCH --vanilla sim_logistic_552.R
R CMD BATCH --vanilla sim_logistic_479.R
R CMD BATCH --vanilla sim_logistic_547.R
R CMD BATCH --vanilla sim_logistic_214.R
R CMD BATCH --vanilla sim_logistic_647.R
R CMD BATCH --vanilla sim_logistic_499.R
R CMD BATCH --vanilla sim_knn_241.R
R CMD BATCH --vanilla sim_knn_724.R
R CMD BATCH --vanilla sim_logistic_436.R
R CMD BATCH --vanilla sim_logistic_607.R
R CMD BATCH --vanilla sim_knn_833.R
R CMD BATCH --vanilla sim_knn_270.R
R CMD BATCH --vanilla sim_logistic_639.R
R CMD BATCH --vanilla sim_knn_143.R
R CMD BATCH --vanilla sim_knn_814.R
R CMD BATCH --vanilla sim_knn_382.R
R CMD BATCH --vanilla sim_logistic_565.R
R CMD BATCH --vanilla sim_logistic_664.R
R CMD BATCH --vanilla sim_logistic_849.R
R CMD BATCH --vanilla sim_knn_513.R
R CMD BATCH --vanilla sim_logistic_330.R
R CMD BATCH --vanilla sim_knn_817.R
R CMD BATCH --vanilla sim_logistic_682.R
R CMD BATCH --vanilla sim_knn_644.R
R CMD BATCH --vanilla sim_knn_135.R
R CMD BATCH --vanilla sim_logistic_260.R
R CMD BATCH --vanilla sim_knn_359.R
R CMD BATCH --vanilla sim_knn_548.R
R CMD BATCH --vanilla sim_knn_299.R
R CMD BATCH --vanilla sim_logistic_464.R
R CMD BATCH --vanilla sim_logistic_311.R
R CMD BATCH --vanilla sim_knn_43.R
R CMD BATCH --vanilla sim_knn_49.R
R CMD BATCH --vanilla sim_logistic_839.R
R CMD BATCH --vanilla sim_logistic_977.R
R CMD BATCH --vanilla sim_logistic_674.R
R CMD BATCH --vanilla sim_knn_562.R
R CMD BATCH --vanilla sim_logistic_650.R
R CMD BATCH --vanilla sim_logistic_648.R
R CMD BATCH --vanilla sim_logistic_43.R
R CMD BATCH --vanilla sim_knn_552.R
R CMD BATCH --vanilla sim_knn_465.R
R CMD BATCH --vanilla sim_logistic_159.R
R CMD BATCH --vanilla sim_logistic_982.R
R CMD BATCH --vanilla sim_logistic_616.R
R CMD BATCH --vanilla sim_logistic_355.R
R CMD BATCH --vanilla sim_knn_661.R
R CMD BATCH --vanilla sim_logistic_701.R
R CMD BATCH --vanilla sim_knn_811.R
R CMD BATCH --vanilla sim_logistic_694.R
R CMD BATCH --vanilla sim_logistic_304.R
R CMD BATCH --vanilla sim_logistic_381.R
R CMD BATCH --vanilla sim_knn_630.R
R CMD BATCH --vanilla sim_knn_73.R
R CMD BATCH --vanilla sim_logistic_299.R
R CMD BATCH --vanilla sim_knn_841.R
R CMD BATCH --vanilla sim_knn_439.R
R CMD BATCH --vanilla sim_knn_889.R
R CMD BATCH --vanilla sim_knn_307.R
R CMD BATCH --vanilla sim_logistic_851.R
R CMD BATCH --vanilla sim_knn_309.R
R CMD BATCH --vanilla sim_logistic_248.R
R CMD BATCH --vanilla sim_knn_450.R
R CMD BATCH --vanilla sim_logistic_241.R
R CMD BATCH --vanilla sim_knn_511.R
R CMD BATCH --vanilla sim_logistic_5.R
R CMD BATCH --vanilla sim_logistic_334.R
R CMD BATCH --vanilla sim_knn_339.R
R CMD BATCH --vanilla sim_logistic_874.R
R CMD BATCH --vanilla sim_knn_234.R
R CMD BATCH --vanilla sim_logistic_878.R
R CMD BATCH --vanilla sim_logistic_392.R
R CMD BATCH --vanilla sim_knn_509.R
R CMD BATCH --vanilla sim_logistic_316.R
R CMD BATCH --vanilla sim_logistic_642.R
R CMD BATCH --vanilla sim_knn_139.R
R CMD BATCH --vanilla sim_logistic_467.R
R CMD BATCH --vanilla sim_logistic_110.R
R CMD BATCH --vanilla sim_logistic_783.R
R CMD BATCH --vanilla sim_logistic_264.R
R CMD BATCH --vanilla sim_logistic_127.R
R CMD BATCH --vanilla sim_knn_396.R
R CMD BATCH --vanilla sim_logistic_128.R
R CMD BATCH --vanilla sim_knn_871.R
R CMD BATCH --vanilla sim_knn_729.R
R CMD BATCH --vanilla sim_knn_958.R
R CMD BATCH --vanilla sim_knn_677.R
R CMD BATCH --vanilla sim_knn_816.R
R CMD BATCH --vanilla sim_knn_91.R
R CMD BATCH --vanilla sim_logistic_377.R
R CMD BATCH --vanilla sim_knn_413.R
R CMD BATCH --vanilla sim_logistic_994.R
R CMD BATCH --vanilla sim_logistic_495.R
R CMD BATCH --vanilla sim_knn_684.R
R CMD BATCH --vanilla sim_logistic_390.R
R CMD BATCH --vanilla sim_logistic_201.R
R CMD BATCH --vanilla sim_knn_516.R
R CMD BATCH --vanilla sim_knn_673.R
R CMD BATCH --vanilla sim_logistic_386.R
R CMD BATCH --vanilla sim_logistic_751.R
R CMD BATCH --vanilla sim_knn_590.R
R CMD BATCH --vanilla sim_knn_343.R
R CMD BATCH --vanilla sim_logistic_610.R
R CMD BATCH --vanilla sim_knn_121.R
R CMD BATCH --vanilla sim_logistic_177.R
R CMD BATCH --vanilla sim_logistic_472.R
R CMD BATCH --vanilla sim_knn_216.R
R CMD BATCH --vanilla sim_logistic_339.R
R CMD BATCH --vanilla sim_knn_261.R
R CMD BATCH --vanilla sim_logistic_453.R
R CMD BATCH --vanilla sim_logistic_194.R
R CMD BATCH --vanilla sim_logistic_556.R
R CMD BATCH --vanilla sim_logistic_764.R
R CMD BATCH --vanilla sim_knn_799.R
R CMD BATCH --vanilla sim_knn_936.R
R CMD BATCH --vanilla sim_knn_93.R
R CMD BATCH --vanilla sim_knn_378.R
R CMD BATCH --vanilla sim_knn_848.R
R CMD BATCH --vanilla sim_knn_789.R
R CMD BATCH --vanilla sim_logistic_889.R
R CMD BATCH --vanilla sim_knn_537.R
R CMD BATCH --vanilla sim_knn_614.R
R CMD BATCH --vanilla sim_logistic_187.R
R CMD BATCH --vanilla sim_logistic_705.R
R CMD BATCH --vanilla sim_logistic_279.R
R CMD BATCH --vanilla sim_logistic_403.R
R CMD BATCH --vanilla sim_knn_842.R
R CMD BATCH --vanilla sim_logistic_103.R
R CMD BATCH --vanilla sim_knn_407.R
R CMD BATCH --vanilla sim_knn_846.R
R CMD BATCH --vanilla sim_logistic_867.R
R CMD BATCH --vanilla sim_knn_356.R
R CMD BATCH --vanilla sim_knn_177.R
R CMD BATCH --vanilla sim_logistic_281.R
R CMD BATCH --vanilla sim_knn_573.R
R CMD BATCH --vanilla sim_logistic_213.R
R CMD BATCH --vanilla sim_knn_62.R
R CMD BATCH --vanilla sim_logistic_872.R
R CMD BATCH --vanilla sim_knn_194.R
R CMD BATCH --vanilla sim_knn_697.R
R CMD BATCH --vanilla sim_logistic_777.R
R CMD BATCH --vanilla sim_knn_719.R
R CMD BATCH --vanilla sim_logistic_229.R
R CMD BATCH --vanilla sim_logistic_574.R
R CMD BATCH --vanilla sim_logistic_408.R
R CMD BATCH --vanilla sim_knn_421.R
R CMD BATCH --vanilla sim_logistic_305.R
R CMD BATCH --vanilla sim_logistic_410.R
R CMD BATCH --vanilla sim_knn_214.R
R CMD BATCH --vanilla sim_logistic_28.R
R CMD BATCH --vanilla sim_logistic_720.R
R CMD BATCH --vanilla sim_logistic_419.R
R CMD BATCH --vanilla sim_knn_37.R
R CMD BATCH --vanilla sim_knn_451.R
R CMD BATCH --vanilla sim_knn_42.R
R CMD BATCH --vanilla sim_knn_648.R
R CMD BATCH --vanilla sim_logistic_309.R
R CMD BATCH --vanilla sim_logistic_412.R
R CMD BATCH --vanilla sim_knn_802.R
R CMD BATCH --vanilla sim_knn_324.R
R CMD BATCH --vanilla sim_knn_484.R
R CMD BATCH --vanilla sim_logistic_871.R
R CMD BATCH --vanilla sim_knn_957.R
R CMD BATCH --vanilla sim_logistic_382.R
R CMD BATCH --vanilla sim_logistic_724.R
R CMD BATCH --vanilla sim_logistic_293.R
R CMD BATCH --vanilla sim_knn_530.R
R CMD BATCH --vanilla sim_knn_92.R
R CMD BATCH --vanilla sim_knn_248.R
R CMD BATCH --vanilla sim_logistic_854.R
R CMD BATCH --vanilla sim_logistic_327.R
R CMD BATCH --vanilla sim_knn_992.R
R CMD BATCH --vanilla sim_knn_823.R
R CMD BATCH --vanilla sim_logistic_638.R
R CMD BATCH --vanilla sim_knn_792.R
R CMD BATCH --vanilla sim_logistic_758.R
R CMD BATCH --vanilla sim_knn_462.R
R CMD BATCH --vanilla sim_logistic_217.R
R CMD BATCH --vanilla sim_knn_519.R
R CMD BATCH --vanilla sim_logistic_530.R
R CMD BATCH --vanilla sim_logistic_428.R
R CMD BATCH --vanilla sim_logistic_645.R
R CMD BATCH --vanilla sim_logistic_343.R
R CMD BATCH --vanilla sim_logistic_259.R
R CMD BATCH --vanilla sim_knn_179.R
R CMD BATCH --vanilla sim_logistic_812.R
R CMD BATCH --vanilla sim_logistic_825.R
R CMD BATCH --vanilla sim_knn_952.R
R CMD BATCH --vanilla sim_logistic_924.R
R CMD BATCH --vanilla sim_logistic_796.R
R CMD BATCH --vanilla sim_knn_773.R
R CMD BATCH --vanilla sim_logistic_790.R
R CMD BATCH --vanilla sim_logistic_773.R
R CMD BATCH --vanilla sim_logistic_981.R
R CMD BATCH --vanilla sim_knn_273.R
R CMD BATCH --vanilla sim_knn_167.R
R CMD BATCH --vanilla sim_knn_294.R
R CMD BATCH --vanilla sim_knn_576.R
R CMD BATCH --vanilla sim_logistic_510.R
R CMD BATCH --vanilla sim_knn_582.R
R CMD BATCH --vanilla sim_knn_965.R
R CMD BATCH --vanilla sim_logistic_811.R
R CMD BATCH --vanilla sim_knn_546.R
R CMD BATCH --vanilla sim_knn_853.R
R CMD BATCH --vanilla sim_knn_229.R
R CMD BATCH --vanilla sim_knn_290.R
R CMD BATCH --vanilla sim_knn_615.R
R CMD BATCH --vanilla sim_logistic_930.R
R CMD BATCH --vanilla sim_logistic_792.R
R CMD BATCH --vanilla sim_knn_166.R
R CMD BATCH --vanilla sim_knn_326.R
R CMD BATCH --vanilla sim_knn_397.R
R CMD BATCH --vanilla sim_knn_834.R
R CMD BATCH --vanilla sim_knn_895.R
R CMD BATCH --vanilla sim_logistic_329.R
R CMD BATCH --vanilla sim_knn_872.R
R CMD BATCH --vanilla sim_knn_993.R
R CMD BATCH --vanilla sim_logistic_336.R
R CMD BATCH --vanilla sim_knn_414.R
R CMD BATCH --vanilla sim_knn_909.R
R CMD BATCH --vanilla sim_knn_1.R
R CMD BATCH --vanilla sim_knn_22.R
R CMD BATCH --vanilla sim_logistic_690.R
R CMD BATCH --vanilla sim_knn_858.R
R CMD BATCH --vanilla sim_logistic_936.R
R CMD BATCH --vanilla sim_logistic_294.R
R CMD BATCH --vanilla sim_knn_336.R
R CMD BATCH --vanilla sim_knn_553.R
R CMD BATCH --vanilla sim_knn_282.R
R CMD BATCH --vanilla sim_logistic_831.R
R CMD BATCH --vanilla sim_knn_345.R
R CMD BATCH --vanilla sim_logistic_220.R
R CMD BATCH --vanilla sim_knn_112.R
R CMD BATCH --vanilla sim_knn_849.R
R CMD BATCH --vanilla sim_logistic_819.R
R CMD BATCH --vanilla sim_knn_532.R
R CMD BATCH --vanilla sim_knn_500.R
R CMD BATCH --vanilla sim_knn_574.R
R CMD BATCH --vanilla sim_logistic_536.R
R CMD BATCH --vanilla sim_logistic_822.R
R CMD BATCH --vanilla sim_knn_984.R
R CMD BATCH --vanilla sim_logistic_345.R
R CMD BATCH --vanilla sim_knn_89.R
R CMD BATCH --vanilla sim_logistic_133.R
R CMD BATCH --vanilla sim_knn_235.R
R CMD BATCH --vanilla sim_knn_213.R
R CMD BATCH --vanilla sim_knn_392.R
R CMD BATCH --vanilla sim_logistic_295.R
R CMD BATCH --vanilla sim_logistic_16.R
R CMD BATCH --vanilla sim_knn_140.R
R CMD BATCH --vanilla sim_knn_315.R
R CMD BATCH --vanilla sim_knn_716.R
R CMD BATCH --vanilla sim_knn_16.R
R CMD BATCH --vanilla sim_knn_423.R
R CMD BATCH --vanilla sim_logistic_209.R
R CMD BATCH --vanilla sim_knn_488.R
R CMD BATCH --vanilla sim_knn_772.R
R CMD BATCH --vanilla sim_logistic_834.R
R CMD BATCH --vanilla sim_knn_735.R
R CMD BATCH --vanilla sim_logistic_85.R
R CMD BATCH --vanilla sim_knn_490.R
R CMD BATCH --vanilla sim_knn_982.R
R CMD BATCH --vanilla sim_logistic_393.R
R CMD BATCH --vanilla sim_knn_412.R
R CMD BATCH --vanilla sim_logistic_501.R
R CMD BATCH --vanilla sim_logistic_842.R
R CMD BATCH --vanilla sim_knn_570.R
R CMD BATCH --vanilla sim_logistic_273.R
R CMD BATCH --vanilla sim_logistic_35.R
R CMD BATCH --vanilla sim_logistic_992.R
R CMD BATCH --vanilla sim_knn_361.R
R CMD BATCH --vanilla sim_logistic_853.R
R CMD BATCH --vanilla sim_logistic_161.R
R CMD BATCH --vanilla sim_knn_320.R
R CMD BATCH --vanilla sim_knn_756.R
R CMD BATCH --vanilla sim_logistic_841.R
R CMD BATCH --vanilla sim_knn_498.R
R CMD BATCH --vanilla sim_logistic_326.R
R CMD BATCH --vanilla sim_logistic_81.R
R CMD BATCH --vanilla sim_logistic_533.R
R CMD BATCH --vanilla sim_logistic_657.R
R CMD BATCH --vanilla sim_knn_168.R
R CMD BATCH --vanilla sim_logistic_29.R
R CMD BATCH --vanilla sim_knn_408.R
R CMD BATCH --vanilla sim_knn_843.R
R CMD BATCH --vanilla sim_knn_145.R
R CMD BATCH --vanilla sim_logistic_972.R
R CMD BATCH --vanilla sim_knn_919.R
R CMD BATCH --vanilla sim_knn_25.R
R CMD BATCH --vanilla sim_knn_115.R
R CMD BATCH --vanilla sim_knn_287.R
R CMD BATCH --vanilla sim_knn_964.R
R CMD BATCH --vanilla sim_logistic_158.R
R CMD BATCH --vanilla sim_knn_891.R
R CMD BATCH --vanilla sim_knn_197.R
R CMD BATCH --vanilla sim_knn_874.R
R CMD BATCH --vanilla sim_knn_281.R
R CMD BATCH --vanilla sim_logistic_291.R
R CMD BATCH --vanilla sim_knn_180.R
R CMD BATCH --vanilla sim_logistic_168.R
R CMD BATCH --vanilla sim_knn_587.R
R CMD BATCH --vanilla sim_logistic_590.R
R CMD BATCH --vanilla sim_knn_598.R
R CMD BATCH --vanilla sim_logistic_487.R
R CMD BATCH --vanilla sim_knn_625.R
R CMD BATCH --vanilla sim_knn_368.R
R CMD BATCH --vanilla sim_logistic_516.R
R CMD BATCH --vanilla sim_logistic_573.R
R CMD BATCH --vanilla sim_logistic_665.R
R CMD BATCH --vanilla sim_knn_354.R
R CMD BATCH --vanilla sim_logistic_532.R
R CMD BATCH --vanilla sim_logistic_465.R
R CMD BATCH --vanilla sim_knn_40.R
R CMD BATCH --vanilla sim_logistic_644.R
R CMD BATCH --vanilla sim_knn_183.R
R CMD BATCH --vanilla sim_logistic_320.R
R CMD BATCH --vanilla sim_knn_956.R
R CMD BATCH --vanilla sim_logistic_167.R
R CMD BATCH --vanilla sim_logistic_984.R
R CMD BATCH --vanilla sim_logistic_576.R
R CMD BATCH --vanilla sim_logistic_765.R
R CMD BATCH --vanilla sim_logistic_451.R
R CMD BATCH --vanilla sim_knn_457.R
R CMD BATCH --vanilla sim_knn_705.R
R CMD BATCH --vanilla sim_logistic_404.R
R CMD BATCH --vanilla sim_knn_508.R
R CMD BATCH --vanilla sim_knn_208.R
R CMD BATCH --vanilla sim_knn_28.R
R CMD BATCH --vanilla sim_logistic_756.R
R CMD BATCH --vanilla sim_logistic_302.R
R CMD BATCH --vanilla sim_logistic_609.R
R CMD BATCH --vanilla sim_logistic_619.R
R CMD BATCH --vanilla sim_logistic_434.R
R CMD BATCH --vanilla sim_logistic_548.R
R CMD BATCH --vanilla sim_knn_471.R
R CMD BATCH --vanilla sim_logistic_117.R
R CMD BATCH --vanilla sim_knn_801.R
R CMD BATCH --vanilla sim_knn_783.R
R CMD BATCH --vanilla sim_logistic_3.R
R CMD BATCH --vanilla sim_logistic_587.R
R CMD BATCH --vanilla sim_logistic_418.R
R CMD BATCH --vanilla sim_logistic_622.R
R CMD BATCH --vanilla sim_knn_355.R
R CMD BATCH --vanilla sim_logistic_813.R
R CMD BATCH --vanilla sim_knn_473.R
R CMD BATCH --vanilla sim_knn_124.R
R CMD BATCH --vanilla sim_logistic_15.R
R CMD BATCH --vanilla sim_logistic_72.R
R CMD BATCH --vanilla sim_logistic_891.R
R CMD BATCH --vanilla sim_logistic_41.R
R CMD BATCH --vanilla sim_logistic_752.R
R CMD BATCH --vanilla sim_knn_918.R
R CMD BATCH --vanilla sim_knn_852.R
R CMD BATCH --vanilla sim_knn_285.R
R CMD BATCH --vanilla sim_logistic_483.R
R CMD BATCH --vanilla sim_knn_260.R
R CMD BATCH --vanilla sim_logistic_179.R
R CMD BATCH --vanilla sim_knn_653.R
R CMD BATCH --vanilla sim_logistic_672.R
R CMD BATCH --vanilla sim_knn_884.R
R CMD BATCH --vanilla sim_logistic_383.R
R CMD BATCH --vanilla sim_knn_164.R
R CMD BATCH --vanilla sim_knn_611.R
R CMD BATCH --vanilla sim_knn_609.R
R CMD BATCH --vanilla sim_knn_704.R
R CMD BATCH --vanilla sim_logistic_519.R
R CMD BATCH --vanilla sim_logistic_197.R
R CMD BATCH --vanilla sim_logistic_716.R
R CMD BATCH --vanilla sim_knn_311.R
R CMD BATCH --vanilla sim_knn_827.R
R CMD BATCH --vanilla sim_logistic_686.R
R CMD BATCH --vanilla sim_logistic_285.R
R CMD BATCH --vanilla sim_knn_606.R
R CMD BATCH --vanilla sim_logistic_509.R
R CMD BATCH --vanilla sim_knn_472.R
R CMD BATCH --vanilla sim_logistic_448.R
R CMD BATCH --vanilla sim_logistic_618.R
R CMD BATCH --vanilla sim_knn_105.R
R CMD BATCH --vanilla sim_knn_836.R
R CMD BATCH --vanilla sim_knn_296.R
R CMD BATCH --vanilla sim_logistic_462.R
R CMD BATCH --vanilla sim_knn_968.R
R CMD BATCH --vanilla sim_logistic_858.R
R CMD BATCH --vanilla sim_knn_187.R
R CMD BATCH --vanilla sim_logistic_84.R
R CMD BATCH --vanilla sim_logistic_909.R
R CMD BATCH --vanilla sim_logistic_150.R
R CMD BATCH --vanilla sim_knn_740.R
R CMD BATCH --vanilla sim_logistic_48.R
R CMD BATCH --vanilla sim_knn_646.R
R CMD BATCH --vanilla sim_knn_390.R
R CMD BATCH --vanilla sim_logistic_492.R
R CMD BATCH --vanilla sim_logistic_520.R
R CMD BATCH --vanilla sim_logistic_346.R
R CMD BATCH --vanilla sim_logistic_397.R
R CMD BATCH --vanilla sim_logistic_808.R
R CMD BATCH --vanilla sim_knn_565.R
R CMD BATCH --vanilla sim_knn_749.R
R CMD BATCH --vanilla sim_logistic_384.R
R CMD BATCH --vanilla sim_logistic_733.R
R CMD BATCH --vanilla sim_logistic_985.R
R CMD BATCH --vanilla sim_logistic_185.R
R CMD BATCH --vanilla sim_logistic_817.R
R CMD BATCH --vanilla sim_knn_825.R
R CMD BATCH --vanilla sim_logistic_654.R
R CMD BATCH --vanilla sim_logistic_543.R
R CMD BATCH --vanilla sim_knn_455.R
R CMD BATCH --vanilla sim_logistic_433.R
R CMD BATCH --vanilla sim_knn_300.R
R CMD BATCH --vanilla sim_logistic_557.R
R CMD BATCH --vanilla sim_logistic_736.R
R CMD BATCH --vanilla sim_knn_900.R
R CMD BATCH --vanilla sim_logistic_358.R
R CMD BATCH --vanilla sim_logistic_980.R
R CMD BATCH --vanilla sim_knn_832.R
R CMD BATCH --vanilla sim_knn_474.R
R CMD BATCH --vanilla sim_logistic_620.R
R CMD BATCH --vanilla sim_knn_293.R
R CMD BATCH --vanilla sim_logistic_242.R
R CMD BATCH --vanilla sim_logistic_598.R
R CMD BATCH --vanilla sim_knn_492.R
R CMD BATCH --vanilla sim_logistic_498.R
R CMD BATCH --vanilla sim_knn_995.R
R CMD BATCH --vanilla sim_logistic_69.R
R CMD BATCH --vanilla sim_knn_525.R
R CMD BATCH --vanilla sim_knn_543.R
R CMD BATCH --vanilla sim_logistic_198.R
R CMD BATCH --vanilla sim_logistic_820.R
R CMD BATCH --vanilla sim_logistic_781.R
R CMD BATCH --vanilla sim_knn_233.R
R CMD BATCH --vanilla sim_knn_103.R
R CMD BATCH --vanilla sim_knn_855.R
R CMD BATCH --vanilla sim_logistic_898.R
R CMD BATCH --vanilla sim_knn_83.R
R CMD BATCH --vanilla sim_logistic_770.R
R CMD BATCH --vanilla sim_logistic_277.R
R CMD BATCH --vanilla sim_knn_924.R
R CMD BATCH --vanilla sim_logistic_45.R
R CMD BATCH --vanilla sim_knn_526.R
R CMD BATCH --vanilla sim_logistic_60.R
R CMD BATCH --vanilla sim_logistic_423.R
R CMD BATCH --vanilla sim_knn_670.R
R CMD BATCH --vanilla sim_logistic_86.R
R CMD BATCH --vanilla sim_logistic_141.R
R CMD BATCH --vanilla sim_logistic_910.R
R CMD BATCH --vanilla sim_logistic_957.R
R CMD BATCH --vanilla sim_logistic_93.R
R CMD BATCH --vanilla sim_logistic_441.R
R CMD BATCH --vanilla sim_knn_126.R
R CMD BATCH --vanilla sim_knn_702.R
R CMD BATCH --vanilla sim_knn_219.R
R CMD BATCH --vanilla sim_logistic_116.R
R CMD BATCH --vanilla sim_knn_788.R
R CMD BATCH --vanilla sim_logistic_357.R
R CMD BATCH --vanilla sim_knn_810.R
R CMD BATCH --vanilla sim_knn_818.R
R CMD BATCH --vanilla sim_knn_383.R
R CMD BATCH --vanilla sim_knn_943.R
R CMD BATCH --vanilla sim_logistic_883.R
R CMD BATCH --vanilla sim_knn_675.R
R CMD BATCH --vanilla sim_knn_898.R
R CMD BATCH --vanilla sim_logistic_470.R
R CMD BATCH --vanilla sim_logistic_20.R
R CMD BATCH --vanilla sim_logistic_940.R
R CMD BATCH --vanilla sim_knn_442.R
R CMD BATCH --vanilla sim_knn_35.R
R CMD BATCH --vanilla sim_knn_386.R
R CMD BATCH --vanilla sim_knn_130.R
R CMD BATCH --vanilla sim_logistic_252.R
R CMD BATCH --vanilla sim_logistic_359.R
R CMD BATCH --vanilla sim_logistic_973.R
R CMD BATCH --vanilla sim_logistic_300.R
R CMD BATCH --vanilla sim_logistic_83.R
R CMD BATCH --vanilla sim_knn_280.R
R CMD BATCH --vanilla sim_knn_597.R
R CMD BATCH --vanilla sim_knn_798.R
R CMD BATCH --vanilla sim_knn_791.R
R CMD BATCH --vanilla sim_knn_128.R
R CMD BATCH --vanilla sim_logistic_762.R
R CMD BATCH --vanilla sim_knn_499.R
R CMD BATCH --vanilla sim_logistic_396.R
R CMD BATCH --vanilla sim_logistic_761.R
R CMD BATCH --vanilla sim_knn_487.R
R CMD BATCH --vanilla sim_logistic_485.R
R CMD BATCH --vanilla sim_logistic_673.R
R CMD BATCH --vanilla sim_knn_551.R
R CMD BATCH --vanilla sim_knn_441.R
R CMD BATCH --vanilla sim_logistic_729.R
R CMD BATCH --vanilla sim_knn_133.R
R CMD BATCH --vanilla sim_logistic_998.R
R CMD BATCH --vanilla sim_logistic_356.R
R CMD BATCH --vanilla sim_knn_428.R
R CMD BATCH --vanilla sim_knn_639.R
R CMD BATCH --vanilla sim_logistic_65.R
R CMD BATCH --vanilla sim_knn_185.R
R CMD BATCH --vanilla sim_logistic_79.R
R CMD BATCH --vanilla sim_knn_880.R
R CMD BATCH --vanilla sim_knn_434.R
R CMD BATCH --vanilla sim_logistic_539.R
R CMD BATCH --vanilla sim_knn_755.R
R CMD BATCH --vanilla sim_knn_712.R
R CMD BATCH --vanilla sim_logistic_827.R
R CMD BATCH --vanilla sim_logistic_183.R
R CMD BATCH --vanilla sim_knn_885.R
R CMD BATCH --vanilla sim_logistic_287.R
R CMD BATCH --vanilla sim_logistic_511.R
R CMD BATCH --vanilla sim_knn_674.R
R CMD BATCH --vanilla sim_logistic_894.R
R CMD BATCH --vanilla sim_logistic_143.R
R CMD BATCH --vanilla sim_logistic_964.R
R CMD BATCH --vanilla sim_knn_672.R
R CMD BATCH --vanilla sim_logistic_39.R
R CMD BATCH --vanilla sim_logistic_324.R
R CMD BATCH --vanilla sim_knn_851.R
R CMD BATCH --vanilla sim_knn_247.R
R CMD BATCH --vanilla sim_knn_775.R
R CMD BATCH --vanilla sim_logistic_658.R
R CMD BATCH --vanilla sim_logistic_455.R
R CMD BATCH --vanilla sim_logistic_480.R
R CMD BATCH --vanilla sim_logistic_919.R
R CMD BATCH --vanilla sim_logistic_615.R
R CMD BATCH --vanilla sim_logistic_266.R
R CMD BATCH --vanilla sim_knn_410.R
R CMD BATCH --vanilla sim_logistic_931.R
R CMD BATCH --vanilla sim_logistic_402.R
R CMD BATCH --vanilla sim_knn_33.R
R CMD BATCH --vanilla sim_logistic_166.R
R CMD BATCH --vanilla sim_knn_765.R
R CMD BATCH --vanilla sim_knn_403.R
R CMD BATCH --vanilla sim_logistic_112.R
R CMD BATCH --vanilla sim_logistic_614.R
R CMD BATCH --vanilla sim_knn_159.R
R CMD BATCH --vanilla sim_logistic_145.R
R CMD BATCH --vanilla sim_logistic_105.R
R CMD BATCH --vanilla sim_logistic_51.R
R CMD BATCH --vanilla sim_knn_862.R
R CMD BATCH --vanilla sim_knn_375.R
R CMD BATCH --vanilla sim_knn_45.R
R CMD BATCH --vanilla sim_knn_510.R
R CMD BATCH --vanilla sim_logistic_193.R
R CMD BATCH --vanilla sim_logistic_437.R
R CMD BATCH --vanilla sim_knn_591.R
R CMD BATCH --vanilla sim_logistic_513.R
R CMD BATCH --vanilla sim_logistic_109.R
R CMD BATCH --vanilla sim_knn_939.R
R CMD BATCH --vanilla sim_logistic_544.R
R CMD BATCH --vanilla sim_logistic_816.R
R CMD BATCH --vanilla sim_logistic_562.R
R CMD BATCH --vanilla sim_knn_618.R
R CMD BATCH --vanilla sim_knn_781.R
R CMD BATCH --vanilla sim_logistic_62.R
R CMD BATCH --vanilla sim_logistic_838.R
R CMD BATCH --vanilla sim_knn_501.R
R CMD BATCH --vanilla sim_logistic_591.R
R CMD BATCH --vanilla sim_logistic_951.R
R CMD BATCH --vanilla sim_logistic_950.R
R CMD BATCH --vanilla sim_logistic_943.R
R CMD BATCH --vanilla sim_knn_419.R
R CMD BATCH --vanilla sim_logistic_268.R
R CMD BATCH --vanilla sim_logistic_677.R
R CMD BATCH --vanilla sim_knn_831.R
R CMD BATCH --vanilla sim_knn_242.R
R CMD BATCH --vanilla sim_knn_813.R
R CMD BATCH --vanilla sim_logistic_176.R
R CMD BATCH --vanilla sim_logistic_450.R
R CMD BATCH --vanilla sim_knn_751.R
R CMD BATCH --vanilla sim_knn_572.R
R CMD BATCH --vanilla sim_knn_77.R
R CMD BATCH --vanilla sim_logistic_49.R
R CMD BATCH --vanilla sim_logistic_270.R
R CMD BATCH --vanilla sim_logistic_421.R
R CMD BATCH --vanilla sim_knn_51.R
R CMD BATCH --vanilla sim_knn_437.R
R CMD BATCH --vanilla sim_knn_922.R
R CMD BATCH --vanilla sim_knn_948.R
R CMD BATCH --vanilla sim_knn_418.R
R CMD BATCH --vanilla sim_knn_56.R
R CMD BATCH --vanilla sim_knn_854.R
R CMD BATCH --vanilla sim_knn_657.R
R CMD BATCH --vanilla sim_logistic_368.R
R CMD BATCH --vanilla sim_logistic_939.R
R CMD BATCH --vanilla sim_logistic_525.R
R CMD BATCH --vanilla sim_logistic_551.R
R CMD BATCH --vanilla sim_knn_279.R
R CMD BATCH --vanilla sim_logistic_791.R
R CMD BATCH --vanilla sim_knn_584.R
R CMD BATCH --vanilla sim_knn_887.R
R CMD BATCH --vanilla sim_logistic_941.R
R CMD BATCH --vanilla sim_knn_643.R
R CMD BATCH --vanilla sim_logistic_577.R
R CMD BATCH --vanilla sim_logistic_546.R
R CMD BATCH --vanilla sim_knn_824.R
R CMD BATCH --vanilla sim_logistic_922.R
R CMD BATCH --vanilla sim_knn_86.R
R CMD BATCH --vanilla sim_knn_867.R
R CMD BATCH --vanilla sim_knn_645.R
R CMD BATCH --vanilla sim_logistic_92.R
R CMD BATCH --vanilla sim_knn_99.R
R CMD BATCH --vanilla sim_logistic_554.R
R CMD BATCH --vanilla sim_logistic_661.R
R CMD BATCH --vanilla sim_logistic_506.R
R CMD BATCH --vanilla sim_knn_39.R
R CMD BATCH --vanilla sim_logistic_814.R
R CMD BATCH --vanilla sim_knn_951.R
R CMD BATCH --vanilla sim_logistic_173.R
R CMD BATCH --vanilla sim_logistic_836.R
R CMD BATCH --vanilla sim_logistic_514.R
R CMD BATCH --vanilla sim_knn_402.R
R CMD BATCH --vanilla sim_knn_961.R
R CMD BATCH --vanilla sim_logistic_27.R
R CMD BATCH --vanilla sim_logistic_731.R
R CMD BATCH --vanilla sim_knn_192.R
R CMD BATCH --vanilla sim_knn_444.R
R CMD BATCH --vanilla sim_logistic_148.R
R CMD BATCH --vanilla sim_knn_5.R
R CMD BATCH --vanilla sim_knn_393.R
R CMD BATCH --vanilla sim_knn_19.R
R CMD BATCH --vanilla sim_logistic_625.R
R CMD BATCH --vanilla sim_logistic_31.R
R CMD BATCH --vanilla sim_knn_987.R
R CMD BATCH --vanilla sim_logistic_952.R
R CMD BATCH --vanilla sim_logistic_604.R
R CMD BATCH --vanilla sim_logistic_956.R
R CMD BATCH --vanilla sim_logistic_439.R
R CMD BATCH --vanilla sim_logistic_130.R
R CMD BATCH --vanilla sim_knn_117.R
R CMD BATCH --vanilla sim_logistic_704.R
R CMD BATCH --vanilla sim_knn_752.R
